Wwise Unity Integration: AkListBare< T, U_NEXTITEM, AkCountPolicyNoCount, AkLastPolicyNoLast >::Remove
AKRESULT AkListBare< T, U_NEXTITEM, AkCountPolicyNoCount , AkLastPolicyNoLast >::Remove (T * in_pItem) [inline, inherited]
Remove an element.
References AK_Fail, AK_Success, AkListBare< T, U_NEXTITEM, COUNT_POLICY, LAST_POLICY >::End(), AkListBare< T, U_NEXTITEM, COUNT_POLICY, LAST_POLICY >::Erase(), and AkListBare< T, U_NEXTITEM, COUNT_POLICY, LAST_POLICY >::FindEx().